name: Deploy Staging

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: ok-nick/setup-aftman@v0.3.0
      name: Install Aftman
      with:
          version: "v0.2.7"
          token: ${{ SECRETS.GITHUB_TOKEN }}

    - run: rojo build -o game.rbxl

#    - run: 