name: Deploy Staging

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: ok-nick/setup-aftman@v0.3.0
      name: Install Aftman
      with:
          version: "v0.2.7"
          token: ${{ SECRETS.GITHUB_TOKEN }}

    - run: rojo build -o game.rbxl

    - run: rbxcloud experience publish -f game.rbxl -p 11706530527 -u 4146637897 -t published -a 1f3B05LmyE2dT1rTnOUqoITJDI9E8RJC8I9lIkROguT7YkzP